# Test for issue #6262: TS OSS validateAndTrimEntityId crashes on non-string (e.g. integer) entity ids
# Auto-generated by PR Harness

import pytest


def test_issue_6262():
    """Regression test for issue #6262."""
    # TODO: implement proper test reproduction
    # Issue: TS OSS validateAndTrimEntityId crashes on non-string (e.g. integer) entity ids
    pass

