# Test for issue #6150: Procedural memory creation crashes with AttributeError instead of a clear error when the LLM returns no content
# Auto-generated by PR Harness

import pytest


def test_issue_6150():
    """Regression test for issue #6150."""
    # TODO: implement proper test reproduction
    # Issue: Procedural memory creation crashes with AttributeError instead of a clear error 
    pass

