# Test for issue #6260: TS OSS search() drops one bound of a same-field range filter (shallow Object.assign)
# Auto-generated by PR Harness

import pytest


def test_issue_6260():
    """Regression test for issue #6260."""
    # TODO: implement proper test reproduction
    # Issue: TS OSS search() drops one bound of a same-field range filter (shallow Object.ass
    pass

