AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB tables for Mem0'

Resources:
  Mem0ConversationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Mem0Conversations
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: conversation_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: conversation_id
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: expiration_time
        Enabled: true

  Mem0GraphTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Mem0Graph
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: node_id
          AttributeType: S
        - AttributeName: edge_id
          AttributeType: S
        - AttributeName: relationship_type
          AttributeType: S
        - AttributeName: created_at
          AttributeType: N
      KeySchema:
        - AttributeName: node_id
          KeyType: HASH
        - AttributeName: edge_id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: RelationshipTypeIndex
          KeySchema:
            - AttributeName: relationship_type
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

Outputs:
  ConversationTableName:
    Description: Name of the conversation table
    Value: !Ref Mem0ConversationTable
  GraphTableName:
    Description: Name of the graph table
    Value: !Ref Mem0GraphTable
