packages:
  - '.'

onlyBuiltDependencies:
  - "@parcel/watcher"
  - sharp

overrides:
  "immutable@>=5.0.0 <5.1.5": "^5.1.5"
  "picomatch@<2.3.2": "^2.3.2"
  "minimatch@>=9.0.0 <9.0.7": "^9.0.7"
  "glob@>=10.2.0 <10.5.0": "^10.5.0"
  "postcss@<8.5.10": ">=8.5.10"
  "yaml@>=2.0.0 <2.8.3": ">=2.8.3"
