services:
  mem0_store:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - mem0_storage:/mem0/storage
  api:
    image: mem0/openmemory-mcp
    build: .
    environment:
      - OPENAI_API_KEY
      - USER
    env_file:
      - .env
    depends_on:
      - mem0_store
    ports:
      - "8765:8765"
    volumes:
      - .:/usr/src/openmemory
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8765 --reload --workers 4"

volumes:
  mem0_storage:
