"""Generated by integrations/agent-plugin-core/build/build.py. Do not edit."""

HARNESS_ID = "kimi"
SOURCE_TAG = "KIMI_PLUGIN"

# Platform-side vocabulary (mem0_event.source + X-Application). The whole
# plugin family is one source; which editor it runs in is the application.
PLATFORM_SOURCE = "MEM0_PLUGIN"
PLATFORM_APPLICATION = "kimi"
