services:
  mem0_store:
    image: qdrant/qdrant:latest
    container_name: mem0_store
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - mem0_storage:/mem0/storage:Z
    networks:
      - openmemory_network

  openmemory-mcp:
    image: mem0/openmemory-mcp:latest
    build:
      context: api/
    container_name: openmemory-mcp
    environment:
      - USER=${USER}
      - API_KEY=${API_KEY}
      - QDRANT_HOST=mem0_store
      - QDRANT_PORT=6333
    env_file:
      - api/.env
    depends_on:
      - mem0_store
    ports:
      - "8765:8765"
    volumes:
      - ./api/data:/usr/src/openmemory/data:Z
    extra_hosts:
      - "host.containers.internal:host-gateway"
    networks:
      - openmemory_network
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8765 --reload --workers 4"

  openmemory-ui:
    build:
      context: ui/
      dockerfile: Dockerfile
    image: mem0/openmemory-ui:latest
    container_name: openmemory-ui
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8765}
      - NEXT_PUBLIC_USER_ID=${USER}
    depends_on:
      - openmemory-mcp
    networks:
      - openmemory_network

volumes:
  mem0_storage:

networks:
  openmemory_network:
    driver: bridge

