packages:
  - '.'

allowBuilds:
  '@google/genai': set this to true or false
  better-sqlite3: set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - protobufjs

overrides:
  "form-data@<4.0.6": ">=4.0.6"
  "protobufjs@<7.5.5": "^7.5.5"
  "vite": "^8.0.5"
  "langsmith@<0.6.0": "^0.6.0"
  "picomatch@<2.3.2": "^2.3.2"
  "@qdrant/js-client-rest": "^1.18.0"
  "uuid@<11.1.1": ">=11.1.1"
  "esbuild": ">=0.28.1"
  "undici@<6.27.0": ">=6.27.0"
