#!/bin/bash
# OpenMemory Fly.io Initial Setup Script
# Run this once to set up both test and production environments

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_DIR="$(dirname "${SCRIPT_DIR}")"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() { echo -e "${GREEN}[SETUP]${NC} $1"; }
info() { echo -e "${BLUE}[INFO]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1" >&2; exit 1; }

echo "=========================================="
echo "   OpenMemory Fly.io Setup"
echo "=========================================="
echo ""

# Check prerequisites
log "Checking prerequisites..."

if ! command -v flyctl &> /dev/null; then
    error "flyctl not found. Install: curl -L https://fly.io/install.sh | sh"
fi

if ! flyctl auth whoami &> /dev/null; then
    error "Not logged in. Run: flyctl auth login"
fi

log "Prerequisites OK"
echo ""

# Generate secrets
log "Generating secure keys..."

AUTH_SECRET_KEY=$(openssl rand -hex 64)
API_MASTER_KEY_PROD=$(openssl rand -hex 32)
API_MASTER_KEY_TEST=$(openssl rand -hex 32)

echo ""
info "Generated keys (SAVE THESE SOMEWHERE SECURE):"
echo ""
echo "Production API Master Key: ${API_MASTER_KEY_PROD}"
echo "Test API Master Key:       ${API_MASTER_KEY_TEST}"
echo ""

# Get OpenAI API Key
echo ""
read -p "Enter your OpenAI API Key: " OPENAI_API_KEY
if [ -z "${OPENAI_API_KEY}" ]; then
    error "OpenAI API Key is required"
fi

# Get Anthropic API Key for Claude security reviews
echo ""
info "Anthropic API Key is used for Claude-powered security reviews"
info "This helps detect backdoors in upstream code before deployment"
read -p "Enter your Anthropic API Key (or press Enter to skip): " ANTHROPIC_API_KEY

# Choose region
echo ""
info "Available regions: sjc (San Jose), iad (Virginia), lhr (London), nrt (Tokyo)"
read -p "Enter region [sjc]: " REGION
REGION="${REGION:-sjc}"

# Create production app
echo ""
log "Creating production app (openmemory-prod)..."

if flyctl apps list | grep -q "openmemory-prod"; then
    warn "App openmemory-prod already exists"
else
    flyctl apps create openmemory-prod --org personal
fi

# Create production volume
log "Creating production volume..."
if ! flyctl volumes list -a openmemory-prod | grep -q "openmemory_data"; then
    flyctl volumes create openmemory_data \
        -a openmemory-prod \
        --region "${REGION}" \
        --size 10 \
        --yes
fi

# Set production secrets
log "Setting production secrets..."
flyctl secrets set -a openmemory-prod \
    OPENAI_API_KEY="${OPENAI_API_KEY}" \
    AUTH_SECRET_KEY="${AUTH_SECRET_KEY}" \
    API_MASTER_KEY="${API_MASTER_KEY_PROD}"

# Create test app
echo ""
log "Creating test app (openmemory-test)..."

if flyctl apps list | grep -q "openmemory-test"; then
    warn "App openmemory-test already exists"
else
    flyctl apps create openmemory-test --org personal
fi

# Create test volume
log "Creating test volume..."
if ! flyctl volumes list -a openmemory-test | grep -q "openmemory_test_data"; then
    flyctl volumes create openmemory_test_data \
        -a openmemory-test \
        --region "${REGION}" \
        --size 1 \
        --yes
fi

# Set test secrets
log "Setting test secrets..."
flyctl secrets set -a openmemory-test \
    OPENAI_API_KEY="${OPENAI_API_KEY}" \
    AUTH_SECRET_KEY="${AUTH_SECRET_KEY}" \
    API_MASTER_KEY="${API_MASTER_KEY_TEST}"

# Update fly.toml with region
log "Updating configuration with region: ${REGION}..."
sed -i.bak "s/primary_region = \"sjc\"/primary_region = \"${REGION}\"/" "${DEPLOY_DIR}/fly.toml"
sed -i.bak "s/primary_region = \"sjc\"/primary_region = \"${REGION}\"/" "${DEPLOY_DIR}/fly-test.toml"
rm -f "${DEPLOY_DIR}/fly.toml.bak" "${DEPLOY_DIR}/fly-test.toml.bak"

# Save local environment for security checks
ENV_FILE="${DEPLOY_DIR}/.env.local"
log "Saving local environment to ${ENV_FILE}..."

cat > "${ENV_FILE}" << EOF
# Local environment for security checks (DO NOT COMMIT)
# Generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

# Anthropic API Key for Claude security reviews
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}

# For local testing (optional)
# OPENAI_API_KEY=${OPENAI_API_KEY}
EOF

chmod 600 "${ENV_FILE}"

# Install Python dependencies for security checks
log "Installing Python dependencies for security checks..."
if command -v pip3 &> /dev/null; then
    pip3 install anthropic bandit safety --quiet || warn "Could not install security tools"
fi

# Install git hooks
log "Installing git hooks..."
"${DEPLOY_DIR}/hooks/install-hooks.sh" || warn "Could not install git hooks"

echo ""
echo "=========================================="
echo "   Setup Complete!"
echo "=========================================="
echo ""
info "Next steps:"
echo ""
echo "1. Set up Claude security reviews (add to your shell profile):"
if [ -n "${ANTHROPIC_API_KEY}" ]; then
    echo "   export ANTHROPIC_API_KEY='${ANTHROPIC_API_KEY}'"
else
    echo "   export ANTHROPIC_API_KEY='your-anthropic-key'"
    warn "   (You skipped this - add it later for AI security reviews)"
fi
echo ""
echo "2. Deploy to test environment:"
echo "   ./scripts/deploy.sh test"
echo ""
echo "3. Test the deployment:"
echo "   curl https://openmemory-test.fly.dev/health"
echo ""
echo "4. Get a token:"
echo "   curl -X POST https://openmemory-test.fly.dev/auth/token \\"
echo "     -H 'X-API-Key: ${API_MASTER_KEY_TEST}' \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"user_id\": \"test-user\", \"scopes\": [\"read\", \"write\"]}'"
echo ""
echo "5. Deploy to production when ready:"
echo "   ./scripts/deploy.sh production"
echo ""
info "Save your API Master Keys securely!"
echo "Production: ${API_MASTER_KEY_PROD}"
echo "Test:       ${API_MASTER_KEY_TEST}"
echo ""
info "For Claude security reviews, ensure ANTHROPIC_API_KEY is exported"
echo ""
