llm:
  provider: google
  config:
    model: gemini-2.5-flash
    max_tokens: 1048576
    temperature: 1.0
    top_p: 0.95
    stream: false

embedder:
  provider: google
  config:
    model: gemini-embedding-001
