packages:
  - '.'

allowBuilds:
  better-sqlite3: set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - protobufjs

overrides:
  "protobufjs@<7.5.5": "^7.5.5"
  "vite": "^8.0.5"
  "langsmith@<0.6.0": "^0.6.0"
  "picomatch@<2.3.2": "^2.3.2"
  "@qdrant/js-client-rest": "^1.18.0"
